language: ruby
rvm:
  - 1.9.3
install: 'bundle install && bundle exec rake appraisal:install'
script: 'bundle exec guard-jasmine --server-timeout=60 && bundle exec rake appraisal test[60]'
notifications:
  email:
    on_success: always
    on_failure: always
