language: ruby
rvm:
  - 1.9.3
install: 'bundle install && bundle exec rake appraisal:install'
script: 'bundle exec rake jasmine:headless && bundle exec rake appraisal jasmine:headless'
notifications:
  email:
    on_success: always
    on_failure: always
